language: ruby
rvm:
- 2.3.3
# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch
script: "bundle exec jekyll build --config _config.travis.yml; bundle exec htmlproofer --only-4xx --url-ignore \"/#.*/,/getting-started\" ./_site"
